name: Hello World Workflow

# This triggers the workflow on push events to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout repository
        run: echo "Hello World"
        shell: bash

  Goodbye-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Goodbye World
        run: echo "Goodbye, World!"
        shell: bash



        
