name: Generate multiple jobs

on: push

jobs:
    build_job1:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Install cowsay
          run: sudo apt install cowsay -y
            
        - name: Generate ASCII artwork
          run: cowsay -f dragon "Run for cover, I am a Dragon....RAWR" >> dragon.txt

        - name: Sleep for 30 secs
          run: sleep 30

    test_job1:
        runs-on: ubuntu-latest
        steps:
        - name: sleep for 10 secs
          run: sleep 10

        - name: Test file exists
          run: grep -i "dragon" dragon.txt
    
          
    deploy_job1:
        runs-on: ubuntu-latest
        steps:
        - name: Read File
          run: cat dragon.txt
                
        - name: Deploy
          run: echo Deploying .. .. ..